// <auto-generated />
using System;
using AuslinkOperatingSupport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AuslinkOperatingSupport.Migrations
{
    [DbContext(typeof(MvcAuslinkContext))]
    partial class MvcAuslinkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuslinkOperatingSupport.Models.ClientClass", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientRateSheetID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ClientClasses");
                });

            modelBuilder.Entity("AuslinkOperatingSupport.Models.ContainerClass", b =>
                {
                    b.Property<string>("ContainerNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChargeFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IfBookedCartage")
                        .HasColumnType("bit");

                    b.Property<bool>("IfCartageOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IfEnteredCartonCloud")
                        .HasColumnType("bit");

                    b.Property<bool>("IfExtraLeg")
                        .HasColumnType("bit");

                    b.Property<bool>("IfInvoiced")
                        .HasColumnType("bit");

                    b.Property<bool>("IfRequireDelivery")
                        .HasColumnType("bit");

                    b.Property<bool>("IfRequireStorage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OceanFreightETA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeToYard")
                        .HasColumnType("datetime2");

                    b.HasKey("ContainerNumber");

                    b.ToTable("ContainerClasses");
                });

            modelBuilder.Entity("AuslinkOperatingSupport.Models.Staff_class", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorityLevel")
                        .HasColumnType("int");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ID");

                    b.ToTable("staff_Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
